const modulesDB = {
    "hsbc_std_base": { type: "always", rate: 0.004, desc: "🐾 基本回贈 (0.4%)" },
    "vs_base": { type: "always", rate: 0.004, desc: "🐾 基本回贈 (0.4%)" },
    "red_hot_variable": { type: "red_hot_allocation", rate_per_x: 0.004, desc: "💖 最紅自主賞", setting_key: "red_hot_rewards_enabled" },
    "vs_red_hot_bonus": { type: "red_hot_fixed_bonus", multiplier: 3, rate_per_x: 0.004, desc: "💎 VS 專屬 (1.2%)" },
    "red_base": { type: "always", rate: 0.004, desc: "🐾 基本回贈 (0.4%)" },
    "red_online": { type: "category", match: ["online"], rate: 0.04, desc: "💻 網購 4%", mode: "replace", cap_mode: "reward", cap_limit: 400, cap_key: "red_online_cap" },
    "red_designated_bonus": { type: "category", match: ["red_designated"], rate: 0.08, desc: "🌟 指定 8%", cap_mode: "reward", cap_limit: 100, cap_key: "red_designated_cap" },
    "em_base": { type: "always", rate: 0.01, desc: "🐾 $5/里 (1%)" },
    "em_designated": { type: "category", match: ["streaming", "transport", "travel"], rate: 0.025, desc: "🚋 指定 $2/里", mode: "replace" },
    "em_overseas_bonus": { type: "category", match: ["overseas", "overseas_jkt", "overseas_tw", "overseas_cn", "overseas_other"], rate: 0.015, desc: "🌍 推廣 +1.5%", setting_key: "em_promo_enabled", cap_mode: "reward", cap_limit: 225, cap_key: "em_promo_cap" },
    "travel_guru_v2": { type: "guru_capped", category: "overseas", config: { 1: { rate: 0.03, cap_rc: 500, desc: "🐣 GO級" }, 2: { rate: 0.04, cap_rc: 1200, desc: "🐥 GING級" }, 3: { rate: 0.06, cap_rc: 2200, desc: "👑 GURU級" } }, usage_key: "guru_rc_used" },
    "mmpower_overseas_bonus": { type: "category", match: ["overseas", "overseas_jkt", "overseas_tw", "overseas_cn", "overseas_other"], rate: 0.056, desc: "✈️ 海外 6%", mode: "add", setting_key: "mmpower_promo_enabled", cap_mode: "reward", cap_limit: 500, cap_key: "mmpower_reward_cap", req_mission_spend: 5000, req_mission_key: "spend_hangseng_mmpower" },
    "mmpower_online_bonus": { type: "category", match: ["online"], rate: 0.046, desc: "💻 網購 5%", mode: "add", setting_key: "mmpower_promo_enabled", cap_mode: "reward", cap_limit: 500, cap_key: "mmpower_reward_cap", req_mission_spend: 5000, req_mission_key: "spend_hangseng_mmpower" },
    "travel_plus_tier1_bonus": { type: "category", match: ["travel_plus_tier1", "overseas_jkt", "overseas_tw"], rate: 0.066, desc: "🇯🇵🇰🇷 指定 7%", mode: "add", setting_key: "travel_plus_promo_enabled", cap_mode: "reward", cap_limit: 500, cap_key: "travel_plus_reward_cap", req_mission_spend: 6000, req_mission_key: "spend_hangseng_travel_plus" },
    "travel_plus_dining_bonus": { type: "category", match: ["dining"], rate: 0.046, desc: "🍱 餐飲 5%", mode: "add", setting_key: "travel_plus_promo_enabled", cap_mode: "reward", cap_limit: 500, cap_key: "travel_plus_reward_cap", req_mission_spend: 6000, req_mission_key: "spend_hangseng_travel_plus" },
    "boc_amazing_weekday": { type: "category", match: ["dining", "travel"], rate: 0.02, desc: "🔥 狂賞派平日 2%", valid_on_red_day: false, setting_key: "boc_amazing_enabled", cap_limit: 120, cap_key: "boc_amazing_local_weekday_cap" },
    "boc_amazing_holiday": { type: "category", match: ["dining", "travel"], rate: 0.05, desc: "🎈 狂賞派紅日 5%", valid_on_red_day: true, setting_key: "boc_amazing_enabled", cap_limit: 300, cap_key: "boc_amazing_local_holiday_cap" },
    "boc_cheers_base": { type: "always", rate: 0.004, desc: "🐾 基本回贈" },
    "boc_cheers_dining": { type: "category", match: ["dining"], rate: 0.04, desc: "🍱 餐飲 10X (4%)", mode: "replace", cap_mode: "reward", cap_limit: 100000, cap_key: "boc_cheers_dining_cap" },
    "boc_cheers_travel": { type: "category", match: ["travel", "overseas"], rate: 0.04, desc: "✈️ 旅遊 10X (4%)", mode: "replace", cap_mode: "reward", cap_limit: 250000, cap_key: "boc_cheers_travel_cap" },
    "sc_smart_base": { type: "always", rate: 0.0055, desc: "🐾 基本 0.55%" },
    "sc_smart_designated": { type: "category", match: ["smart_designated", "grocery"], rate: 0.05, desc: "🛒 指定 5%", mode: "replace", cap_limit: 60000, cap_key: "sc_smart_cap" },
    "sc_simply_cash_base": { type: "always", rate: 0.015, desc: "🐾 本地 1.5%" },
    "sc_simply_cash_foreign": { type: "category", match: ["overseas"], rate: 0.02, desc: "🌍 外幣 2%", mode: "replace" },
    "aeon_waku_base": { type: "always", rate: 0.005, desc: "🐾 基本 0.5%" },
    "aeon_waku_online": { type: "category", match: ["online"], rate: 0.06, desc: "🎎 網購 6%", mode: "replace", cap_limit: 300, cap_key: "aeon_waku_cap" },
    "earnmore_base": { type: "always", rate: 0.02, desc: "💪 全能 2%", cap_limit: 150000, cap_key: "earnmore_annual_spend" },
    "hangseng_base": { type: "always", rate: 0.004, desc: "🐾 基本 0.4%" }
};
